server:
  port: 9092
spring:
  redis:
    host: localhost
    password: sOmE_sEcUrE_pAsS
    port: 6379
  main:
    allow-bean-definition-overriding: true
  jackson:
    serialization:
      write_dates_as_timestamps: false

redis:
  pubsub:
    topic: user-messages