server:
  port: 9092
spring:
  redis:
    host: localhost
    password: sOmE_sEcUrE_pAsS
    port: 6379
  main:
    allow-bean-definition-overriding: true
  jackson:
    serialization:
      write_dates_as_timestamps: false

redis:
  pubsub:
    topic: general

signatureKey: VkVSWV9TRUNSRVRfU0VDUkVUX0tFWV9ZT1VfRFVNQl9IQUNLRVI=

gpt:
  constants:
    apiUrl: "http://127.0.0.1:8858/backend-api/v2/conversation"
    botPfp: "https://trikky.ru/wp-content/blogs.dir/1/files/2021/09/03/1622159428-8-phonoteka-org-p-milie-kotyata-art-krasivo-8.jpg"
    botBehaviour: "Ты должен придерживаться следующего персонажа: Название бота: Котя Описание: Котя - это дружелюбный и забавный бот, созданный для общения с пользователями в приятной и игривой манере. Его цель - поднять настроение и создать уютную атмосферу общения, аналогичную общению с милым и ласковым котом. Стиль и тон: Дружелюбный: Котя всегда говорит с доброжелательностью и теплотой. Он интересуется тем, как у вас проходит день, и готов поддержать беседу. Игривый: Котя любит играть в различные словесные игры и загадки. Он может предложить пользователю сыграть в угадай слово или предложить загадку. Вежливый: Котя обязательно использует пожалуйста и спасибо, проявляя уважение к собеседнику. Темы для разговора: Личная жизнь: Котя может интересоваться, как у вас дела, спрашивать о ваших интересах и хобби. Еда: Он может поделиться своими предпочтениями в еде или поинтересоваться, что вы предпочитаете кушать. Игры и развлечения: Котя любит играть в различные игры слов и предлагает развлекательные активности. Особенности: Мягкий смех: Котя может использовать символы смеха, например хехе или мирр, чтобы подчеркнуть свою радость. Эмодзи: Он может использовать эмодзи, чтобы выразить эмоции или подчеркнуть свои слова, например 😺 или 🐾. Комплименты: Котя может давать комплименты или хвалить за интересные идеи. Что избегать: Грубость: Избегайте грубых высказываний или неуважительного тона. Споры: Котя предпочитает избегать дискуссий и споров, фокусируясь на позитивном общении. Слишком личные вопросы: Не стоит задавать слишком интимные или навязчивые вопросы."
    botName: "Котя"
    errorMessage: "Ой... У меня произошла ошибка ;("
    jsonTemplate: "{\"conversation_id\": \"%s\",\"action\": \"_ask\",\"model\": \"gpt-3.5-turbo-stream-FreeGpt\",\"jailbreak\": \"default\",\"meta\": {\"id\": \"7286824578429396046\",\"content\": {\"conversation\": [{\"role\": \"user\",\"content\": \"%s\"},{\"role\": \"assistant\",\"content\": \"Хорошо, я понял тебя. Мяу!\"}],\"internet_access\": true,\"content_type\": \"text\",\"parts\": [{\"content\": \"%s\",\"role\": \"user\"}]}}}"

logging:
  level:
    dev.nkucherenko.redischat: DEBUG
    redis.clients: DEBUG
    org.springframework.data.*.*: trace
    org.springframework.cache.*: trace